export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_MISSING = 'AUTH_REFRESH_TOKEN_MISSING',

  // Authorization
  AUTHZ_FORBIDDEN = 'AUTHZ_FORBIDDEN',
  AUTHZ_ADMIN_REQUIRED = 'AUTHZ_ADMIN_REQUIRED',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',

  // Resource
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  RESOURCE_OPERATION_FAILED = 'RESOURCE_OPERATION_FAILED',
  SUBJECT_CODE_DUPLICATE = 'SUBJECT_CODE_DUPLICATE',
  SUBJECT_NAME_DUPLICATE = 'SUBJECT_NAME_DUPLICATE',
  SECTION_NAME_DUPLICATE = 'SECTION_NAME_DUPLICATE',
  LECTURE_TITLE_DUPLICATE = 'LECTURE_TITLE_DUPLICATE',
  RESOURCE_LABEL_DUPLICATE = 'RESOURCE_LABEL_DUPLICATE',
  RESOURCE_URL_DUPLICATE = 'RESOURCE_URL_DUPLICATE',
  RESOURCE_URL_INVALID = 'RESOURCE_URL_INVALID',
  PROFILE_EMAIL_DUPLICATE = 'PROFILE_EMAIL_DUPLICATE',
  PROFILE_STUDENT_ID_DUPLICATE = 'PROFILE_STUDENT_ID_DUPLICATE',
  CALENDAR_TIME_RANGE_INVALID = 'CALENDAR_TIME_RANGE_INVALID',
  CALENDAR_EVENT_TIME_CONFLICT = 'CALENDAR_EVENT_TIME_CONFLICT',

  // System
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_EXTERNAL_SERVICE_ERROR = 'SYSTEM_EXTERNAL_SERVICE_ERROR',
}
